jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      ...

  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      ...

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    environment: dev
    steps:
      ...
